name: mobx_app_architecture
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # This is for language selection
    sdk: flutter

  path: any # This is for path
  uuid: ^4.5.1 # This is for uuid
  intl: ^0.19.0 # This is for time format
  cupertino_icons: ^1.0.6 # This is for icons
  firebase_core: ^3.9.0 # This is for firebase
  dio: ^5.4.3+1 # This is for API services call
  url_launcher: ^6.3.1 # This is for launch url
  flutter_blurhash: ^0.8.2 # This is for blurhash
  flutter_svg: ^2.0.10+1 # This is for Load SVG icons
  permission_handler: ^11.3.1 # This is for permission
  mobx: ^2.3.3+2 # This if for flutter state management
  cached_network_image: ^3.4.1 # This is for image caching
  flutter_modular: ^6.3.3 # This is for flutter MVC standar
  shared_preferences: ^2.0.15 # This is for shared preferences
  awesome_notifications: ^0.10.0 # This is for notification
  awesome_notifications_fcm: ^0.10.0 # This is for notification
  flutter_mobx: ^2.2.1+1 # This if for flutter state management
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:

  uses-material-design: true
  generate: true # Auto genrate folder for language

  assets:
    - assets/
    - assets/svg/
    - assets/png/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
